# Generated by Django 4.1 on 2022-08-27 03:01

import KTApp.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('KTApp', '0003_kotercontact_alter_koterconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotercontact',
            name='id',
            field=models.CharField(default=KTApp.models.get_contact_id, editable=False, max_length=18, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kotercontact',
            name='optin_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Optin Date'),
        ),
        migrations.AlterField(
            model_name='kotercontact',
            name='optout_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Optout Date'),
        ),
        migrations.AlterField(
            model_name='kotercontact',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
