# Generated by Django 4.1 on 2022-08-27 03:39

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('KTApp', '0005_koterintegrationuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koterintegrationuser',
            options={'verbose_name': 'Integration User', 'verbose_name_plural': 'Integration Users'},
        ),
        migrations.AddField(
            model_name='kotercontact',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Address'),
        ),
    ]
