# Generated by Django 4.1 on 2022-08-28 01:48

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('KTApp', '0006_alter_koterintegrationuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoterSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('cbc', models.BooleanField(default=None, help_text='User can be contacted (general)?', null=True, verbose_name='Can be contacted')),
                ('cbc_email', models.BooleanField(default=None, null=True, verbose_name='Can be contacted by email')),
                ('cbc_sms', models.BooleanField(default=None, null=True, verbose_name='Can be contacted by sms')),
                ('cbc_whatsapp', models.BooleanField(default=None, null=True, verbose_name='Can be contacted by Whatsapp')),
                ('cbc_facebook', models.BooleanField(default=None, null=True, verbose_name='Can be contacted by Facebook')),
                ('cbc_telegram', models.BooleanField(default=None, null=True, verbose_name='Can be contacted by Telegram')),
                ('contacts', models.ManyToManyField(blank=True, db_index=True, to='KTApp.kotercontact', verbose_name='Contacts')),
                ('countries', models.ManyToManyField(blank=True, db_index=True, to='address.country', verbose_name='Countries')),
                ('localities', models.ManyToManyField(blank=True, db_index=True, to='address.locality', verbose_name='Locality')),
                ('states', models.ManyToManyField(blank=True, db_index=True, to='address.state', verbose_name='State')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='KTApp.taggedcontact', verbose_name='Tags')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
