# Generated by Django 4.1 on 2022-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTApp', '0007_kotersegments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kotersegments',
            options={'verbose_name': 'Segment', 'verbose_name_plural': 'Segments'},
        ),
        migrations.AddField(
            model_name='kotersegments',
            name='need_refresh',
            field=models.BooleanField(default=True, editable=False, verbose_name='Need a refresh'),
        ),
    ]
