# Generated by Django 4.1 on 2022-08-28 15:47

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KTApp', '0008_alter_kotersegments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoterIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('name', models.CharField(db_index=True, max_length=90, verbose_name='Name')),
                ('gateway', models.CharField(choices=[('KTR', 'Köter')], max_length=3, unique=True, verbose_name='Gateway')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='koterconfiguration',
            name='enable_rest_api',
            field=models.BooleanField(default=False, help_text='Open Access Manager Rest API', verbose_name='Enable REST API'),
        ),
        migrations.AddField(
            model_name='koterintegrationuser',
            name='integration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KTApp.koterintegration', verbose_name='Integration'),
            preserve_default=False,
        ),
    ]
